## Order Management Local Configuration

#Postgres Database Config

## DEV -
#spring.datasource.url=jdbc:postgresql://ep-morning-smoke-aosjpzwe-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_8JA5OguletFH

spring.jpa.show-sql=true

# Swagger enabled for local
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=update



