spring.application.name=order-management

server.error.include-stacktrace=never
# Base URI
server.servlet.context-path=/order-management
spring.profiles.active=local

# Server Port
server.port=8081

# H2 Database Config
spring.datasource.url=jdbc:h2:file:./data/order-management;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Hibernate dialect for H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Control Hikari connection pool size
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=3000

# JWT Secret Key
jwt.secret=MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
# 1 hour in milliseconds
jwt.access.expiry=3600000
# 1 day in milliseconds
jwt.refresh.expiry=86400000

# Spring Security Config
security.allow-credentials=false

security.allowed-origins=*
security.allowed-headers=*
security.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS

security.allowed-public-apis[0]=/favicon.ico
security.allowed-public-apis[1]=/session/login
security.allowed-public-apis[2]=/public/**
security.allowed-public-apis[3]=/public/v1/login/*
security.allowed-public-apis[4]=/public/**
security.allowed-public-apis[5]=/h2-console/**

security.exposed-headers[0]=X-Xsrf-Token
